language: python
python: 3.6

sudo: required
dist: trusty

env:
  global:
    - >
      STATUS=$'curl -so/dev/null --user "$EMBARC_BOT" --request POST
      https://api.github.com/repos/$TRAVIS_REPO_SLUG/statuses/${TRAVIS_PULL_REQUEST_SHA:-$TRAVIS_COMMIT}
      --data @- << DATA\n{
      "state": "$0",
      "description": "$1",
      "context": "travis-ci/$NAME",
      "target_url": "https://travis-ci.org/$TRAVIS_REPO_SLUG/jobs/$TRAVIS_JOB_ID"
      }\nDATA'
    - EXPECTED=".ci/expected.ini"
    - TOOLCHAIN_VER="latest"

cache:
  pip: true
  directories:
    - .cache/result
    - .cache/toolchain 

before_install:
  # setup git
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - >
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      diff=$(git diff FETCH_HEAD master .ci)
      if [ "$diff" == "" ]; then
        git checkout remotes/origin/master -- .ci
      fi
    fi
  - bash .ci/before_install.sh

after_success:
  - bash -c "$STATUS" success "Local $NAME testing has passed"

after_failure:
  - bash -c "$STATUS" failure "Local $NAME testing has failed"

script:
  - bash .ci/script.sh

matrix:
  include:
    - env: NAME="emsk-11-gnu_latest" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="11" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc

    - env: NAME="emsk-22-gnu_latest" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="22" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc

    - env: NAME="emsk-23-gnu_latest" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="23" PARALLEL=8 EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc

    - env: NAME="hsdk-gnu-latest" OSP_ROOT="." TOOLCHAIN="gnu" BOARD="hsdk" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc

    - env: NAME="iotdk-gnu-latest" OSP_ROOT="." TOOLCHAIN="gnu" BOARD="iotdk" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc

    - env: NAME="nsim-gnu-latest" OSP_ROOT="." TOOLCHAIN="gnu"  BOARD="nsim" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc

    - env: NAME="emsdp-gnu-latest" OSP_ROOT="." TOOLCHAIN="gnu"  BOARD="emsdp" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc