language: python
python: 2.7

sudo: required
dist: trusty

env:
  global:
    - >
      STATUS=$'curl -so/dev/null --user "$EMBARC_BOT" --request POST
      https://api.github.com/repos/$TRAVIS_REPO_SLUG/statuses/${TRAVIS_PULL_REQUEST_SHA:-$TRAVIS_COMMIT}
      --data @- << DATA\n{
      "state": "$0",
      "description": "$1",
      "context": "travis-ci/$NAME",
      "target_url": "https://travis-ci.org/$TRAVIS_REPO_SLUG/jobs/$TRAVIS_JOB_ID"
      }\nDATA'
    - EXPECTED=".travis/expected.ini"

cache:
  pip: true
  directories:
    - $HOME/.cache/result
    - $HOME/.cache/toolchain 

before_install:
  - bash .travis/before_install.sh
  # setup git
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"

after_success:
  - bash -c "$STATUS" success "Local $NAME testing has passed"

after_failure:
  - bash -c "$STATUS" failure "Local $NAME testing has failed"

script:
  - bash .travis/script.sh

matrix:
  include:
    - env: NAME="emsk-gnu-201709-11" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="11" GNU_VER="2017.09" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc
    - env: NAME="emsk-gnu-201803-11" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="11" GNU_VER="2018.03" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc
    - env: NAME="emsk-gnu-201709-22" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="22" GNU_VER="2017.09" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc
    - env: NAME="emsk-gnu-201803-22" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="22" GNU_VER="2018.03" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc
    - env: NAME="emsk-gnu-201709-23" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="23" GNU_VER="2017.09" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc
    - env: NAME="emsk-gnu-201803-23" OSP_ROOT="." BOARD="emsk" TOOLCHAIN="gnu" BD_VER="23" GNU_VER="2018.03" EXAMPLES="embarc_applications"
      os: linux
      compiler: gcc    
